#!/bin/bash

#Job Name
#BSUB -J fastqc_posttrim_2ndStage[1-962]%50

#Project
#BSUB -P fun_gen_1

#Queue
#BSUB -q normal

#Cores
#BSUB -n 1

#RAM per core (Use M and G for Mb and Gb)
#BSUB -R "rusage[mem=700M]"

#Walltime (HH:MM)
#BSUB -W 00:15

#Output File (Absolute path! Can use job name variable)
#BSUB -o /home/mae120/logs/microhabSel_LC-WGS/fastqc_posttrim_2ndStage.out

###################################################################
#SETUP
#Load Modules
#ml anaconda3/biohpc

#Change Directory
cd /projects2/rsmas/dcrawford/MAE/microhabSel_LC-WGS/trimmed/2ndStage

#Extract sample and parameters using job index. Remember to account for the header in the sample table.
SAMPLE_ID=$(awk -v jindex=$LSB_JOBINDEX 'NR==jindex+1 {print $3}' /projects2/rsmas/dcrawford/MAE/microhabSel_LC-WGS/sample_table.tsv)

#Print which sample is being processed in color.
GREEN='\033[32;1m'
COL_RESET='\033[0m'
echo -e "${GREEN}Processing sample ${SAMPLE_ID}${COL_RESET}"

#CODE
fastqc -o /projects2/rsmas/dcrawford/MAE/microhabSel_LC-WGS/trimmed/fastqc/2ndStage $SAMPLE_ID*
