#!/bin/bash

#Job Name and array call. Square brackets = array size, % = max. number of jobs to run at a time.
#BSUB -J sam2bamSort_1stStage[1-962]%10

#Project
#BSUB -P fun_gen_1

#Queue
#BSUB -q general

#Cores (Max 40)
#BSUB -n 4

#RAM per core (Mb). The second part forces all cores on the same host.
#BSUB -R "rusage[mem=3500] span[hosts=1]"

#Walltime
#BSUB -W 00:20

#Output File (Absolute path! The -oo option overwrites the the output file.)
#BSUB -o /nethome/mae120/logs/microhabSel_LC-WGS/sam2bamSort_1stStage.out

###################################################################
#SETUP
#Load Modules
#Change Directory
cd /projects2/rsmas/dcrawford/MAE/microhabSel_LC-WGS/bam/1stStage

#Extract sample and parameters using job index. Remember to account for the header in the sample table.
SAMPLE_ID=$(awk -v jindex=$LSB_JOBINDEX 'NR==jindex+1 {print $3}' /projects2/rsmas/dcrawford/MAE/microhabSel_LC-WGS/sample_table.tsv)

#Print which sample is being processed in color.
GREEN='\033[32;1m'
COL_RESET='\033[0m'
echo -e "${GREEN}Processing sample ${SAMPLE_ID}${COL_RESET}"

#CODE
sambamba view -t $LSB_DJOB_NUMPROC -S -f bam $SAMPLE_ID'_1stStage.sam' | sambamba sort -t $LSB_DJOB_NUMPROC -m 3G -o $SAMPLE_ID'_1stStage.sorted.bam' /dev/stdin && rm $SAMPLE_ID'_1stStage.sam'